// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleDocumentDataSlicesSlice = BrunoTextSlice;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Categorie field in *Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.categorie
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  categorie: prismic.ContentRelationshipField<"blog_categorie">;

  /**
   * TitleArticle field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.titlearticle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titlearticle: prismic.RichTextField;

  /**
   * DescriptionArticle field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.descriptionarticle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriptionarticle: prismic.RichTextField;

  /**
   * Date de creation field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article.date_de_creation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_de_creation: prismic.DateField;

  /**
   * picture field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice> /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type AssuranceDocumentDataSlicesSlice = FirstSectionSlice | FifthSectionSlice;

/**
 * Content for Assurance documents
 */
interface AssuranceDocumentData {
  /**
   * Slice Zone field in *Assurance*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: assurance.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AssuranceDocumentDataSlicesSlice> /**
   * Meta Description field in *Assurance*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: assurance.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Assurance*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: assurance.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Assurance*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: assurance.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Assurance document from Prismic
 *
 * - **API ID**: `assurance`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AssuranceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AssuranceDocumentData>,
    "assurance",
    Lang
  >;

type BlogDocumentDataSlicesSlice = never;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Title field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * paragraph field in *Blog*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * picture field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.picture
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BlogDocumentData>, "blog", Lang>;

/**
 * Content for Blog Categorie documents
 */
interface BlogCategorieDocumentData {
  /**
   * Name field in *Blog Categorie*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_categorie.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Blog Categorie document from Prismic
 *
 * - **API ID**: `blog_categorie`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategorieDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategorieDocumentData>,
    "blog_categorie",
    Lang
  >;

/**
 * Content for Cookie documents
 */
interface CookieDocumentData {
  /**
   * Title field in *Cookie*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text field in *Cookie*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.txt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  txt: prismic.RichTextField;

  /**
   * Button - Text field in *Cookie*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cookie.btntxt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btntxt: prismic.KeyTextField;
}

/**
 * Cookie document from Prismic
 *
 * - **API ID**: `cookie`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CookieDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CookieDocumentData>,
    "cookie",
    Lang
  >;

/**
 * Item in *Footer → Socials*
 */
export interface FooterDocumentDataSocialsItem {
  /**
   * SocialsLogo field in *Footer → Socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].socialslogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  socialslogo: prismic.ImageField<never>;

  /**
   * SocialsLink field in *Footer → Socials*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].socialslink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  socialslink: prismic.LinkField;
}

type FooterDocumentDataSlices1Slice = FooterSlice;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * StoikLogo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.stoiklogo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  stoiklogo: prismic.ImageField<never>;

  /**
   * StoikLink field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.stoiklink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  stoiklink: prismic.LinkField;

  /**
   * Socials field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<FooterDocumentDataSocialsItem>>;

  /**
   * Paragraph field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.paragraph
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * logos field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logos: prismic.ImageField<never> /**
   * Slice Zone field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices1[]
   * - **Tab**: ColumnSection
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<FooterDocumentDataSlices1Slice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<FooterDocumentData>, "footer", Lang>;

/**
 * Item in *Header → ButtonChoice*
 */
export interface HeaderDocumentDataButtonchoiceItem {
  /**
   * LinkButtonChoice field in *Header → ButtonChoice*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.buttonchoice[].linkbuttonchoice
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbuttonchoice: prismic.LinkField;

  /**
   * LinkLabelChoice field in *Header → ButtonChoice*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.buttonchoice[].linklabelchoice
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  linklabelchoice: prismic.RichTextField;
}

/**
 * Item in *Header → LowTitle*
 */
export interface HeaderDocumentDataLowtitleItem {
  /**
   * LowTitleLink field in *Header → LowTitle*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.lowtitle[].lowtitlelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  lowtitlelink: prismic.LinkField;

  /**
   * LowTitleTitle field in *Header → LowTitle*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.lowtitle[].lowtitletitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  lowtitletitle: prismic.RichTextField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * LogoLink field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logolink
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  logolink: prismic.LinkField;

  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Language field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.language
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  language: prismic.ImageField<never>;

  /**
   * ButtonLabel field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.buttonlabel
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  buttonlabel: prismic.RichTextField;

  /**
   * ButtonArrow field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.buttonarrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  buttonarrow: prismic.ImageField<never>;

  /**
   * ButtonChoice field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.buttonchoice[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  buttonchoice: prismic.GroupField<
    Simplify<HeaderDocumentDataButtonchoiceItem>
  >;

  /**
   * LowTitle field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.lowtitle[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  lowtitle: prismic.GroupField<Simplify<HeaderDocumentDataLowtitleItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type HomeDocumentDataSlicesSlice =
  | FifthSectionSlice
  | FourthSectionSlice
  | ThirdSectionSlice
  | SecondSectionSlice
  | FirstSectionSlice
  | HeroSlice
  | BannerSlice
  | BrunoTextSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

type LegalsDocumentDataSlicesSlice = HeroLegalsSlice | BrunoTextSlice;

/**
 * Content for Legals documents
 */
interface LegalsDocumentData {
  /**
   * Slice Zone field in *Legals*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legals.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<LegalsDocumentDataSlicesSlice> /**
   * Meta Description field in *Legals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legals.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Legals*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legals.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Legals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legals.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Legals document from Prismic
 *
 * - **API ID**: `legals`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<LegalsDocumentData>, "legals", Lang>;

/**
 * Item in *Logo bank → Logo bank - Group*
 */
export interface LogoBankDocumentDataGrpItem {
  /**
   * Logo field in *Logo bank → Logo bank - Group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_bank.grp[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Content for Logo bank documents
 */
interface LogoBankDocumentData {
  /**
   * Logo bank - Group field in *Logo bank*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_bank.grp[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grp: prismic.GroupField<Simplify<LogoBankDocumentDataGrpItem>>;
}

/**
 * Logo bank document from Prismic
 *
 * - **API ID**: `logo_bank`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LogoBankDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LogoBankDocumentData>,
    "logo_bank",
    Lang
  >;

type P404DocumentDataSlicesSlice = Hero404Slice;

/**
 * Content for p404 documents
 */
interface P404DocumentData {
  /**
   * Slice Zone field in *p404*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: p404.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<P404DocumentDataSlicesSlice> /**
   * Meta Title field in *p404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: p404.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *p404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: p404.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *p404*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: p404.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * p404 document from Prismic
 *
 * - **API ID**: `p404`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type P404Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<P404DocumentData>, "p404", Lang>;

/**
 * Item in *Redirect → Redirect*
 */
export interface RedirectDocumentDataRedirectItem {
  /**
   * Source field in *Redirect → Redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /lang/page
   * - **API ID Path**: redirect.redirect[].source
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  source: prismic.KeyTextField;

  /**
   * Destination field in *Redirect → Redirect*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /lang/page
   * - **API ID Path**: redirect.redirect[].destination
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  destination: prismic.KeyTextField;
}

/**
 * Content for Redirect documents
 */
interface RedirectDocumentData {
  /**
   * Redirect field in *Redirect*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: redirect.redirect[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  redirect: prismic.GroupField<Simplify<RedirectDocumentDataRedirectItem>>;
}

/**
 * Redirect document from Prismic
 *
 * - **API ID**: `redirect`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedirectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RedirectDocumentData>,
    "redirect",
    Lang
  >;

/**
 * Item in *Share article → Share article - Group*
 */
export interface ShareArticleDocumentDataGrpItem {
  /**
   * Icon field in *Share article → Share article - Group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: share_article.grp[].icn
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icn: prismic.ImageField<never>;

  /**
   * Link (base url) field in *Share article → Share article - Group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: share_article.grp[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Content for Share article documents
 */
interface ShareArticleDocumentData {
  /**
   * Title field in *Share article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: share_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Share article - Group field in *Share article*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: share_article.grp[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grp: prismic.GroupField<Simplify<ShareArticleDocumentDataGrpItem>>;
}

/**
 * Share article document from Prismic
 *
 * - **API ID**: `share_article`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ShareArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ShareArticleDocumentData>,
    "share_article",
    Lang
  >;

/**
 * Item in *Social Media → Social media - Group*
 */
export interface SocialMediaDocumentDataGrpItem {
  /**
   * Icon field in *Social Media → Social media - Group*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.grp[].icn
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icn: prismic.ImageField<never>;

  /**
   * Link field in *Social Media → Social media - Group*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.grp[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Social Media documents
 */
interface SocialMediaDocumentData {
  /**
   * Title field in *Social Media*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Social media - Group field in *Social Media*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_media.grp[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  grp: prismic.GroupField<Simplify<SocialMediaDocumentDataGrpItem>>;
}

/**
 * Social Media document from Prismic
 *
 * - **API ID**: `social_media`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SocialMediaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SocialMediaDocumentData>,
    "social_media",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | AssuranceDocument
  | BlogDocument
  | BlogCategorieDocument
  | CookieDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | LegalsDocument
  | LogoBankDocument
  | P404Document
  | RedirectDocument
  | ShareArticleDocument
  | SocialMediaDocument;

/**
 * Primary content in *Banner → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Text field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * En savoir plus field in *Banner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.en_savoir_plus
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  en_savoir_plus: prismic.RichTextField;

  /**
   * Link field in *Banner → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *FifthSection → Primary*
 */
export interface FifthSectionSliceDefaultPrimary {
  /**
   * Title field in *FifthSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifth_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph field in *FifthSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifth_section.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * ButtonLabel field in *FifthSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifth_section.primary.buttonlabel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  buttonlabel: prismic.RichTextField;

  /**
   * ButtonLink field in *FifthSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fifth_section.primary.buttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonlink: prismic.LinkField;

  /**
   * BGColor field in *FifthSection → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: fifth_section.primary.bgcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bgcolor: prismic.SelectField<"blue" | "purple">;
}

/**
 * Primary content in *FifthSection → Items*
 */
export interface FifthSectionSliceDefaultItem {
  /**
   * Logo field in *FifthSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fifth_section.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for FifthSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FifthSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FifthSectionSliceDefaultPrimary>,
  Simplify<FifthSectionSliceDefaultItem>
>;

/**
 * Primary content in *FifthSection → Primary*
 */
export interface FifthSectionSliceNobuttonPrimary {
  /**
   * Title field in *FifthSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifth_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph field in *FifthSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fifth_section.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Primary content in *FifthSection → Items*
 */
export interface FifthSectionSliceNobuttonItem {
  /**
   * Logo field in *FifthSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fifth_section.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * nobutton variation for FifthSection Slice
 *
 * - **API ID**: `nobutton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FifthSectionSliceNobutton = prismic.SharedSliceVariation<
  "nobutton",
  Simplify<FifthSectionSliceNobuttonPrimary>,
  Simplify<FifthSectionSliceNobuttonItem>
>;

/**
 * Slice variation for *FifthSection*
 */
type FifthSectionSliceVariation =
  | FifthSectionSliceDefault
  | FifthSectionSliceNobutton;

/**
 * FifthSection Shared Slice
 *
 * - **API ID**: `fifth_section`
 * - **Description**: FifthSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FifthSectionSlice = prismic.SharedSlice<
  "fifth_section",
  FifthSectionSliceVariation
>;

/**
 * Primary content in *FirstSection → Primary*
 */
export interface FirstSectionSliceDefaultPrimary {
  /**
   * Title field in *FirstSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph field in *FirstSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * LinkBox1 field in *FirstSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.linkbox1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbox1: prismic.LinkField;

  /**
   * Picture1Box1 field in *FirstSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.picture1box1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture1box1: prismic.ImageField<never>;

  /**
   * Picture2Box1 field in *FirstSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.picture2box1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture2box1: prismic.ImageField<never>;

  /**
   * TitleBox1 field in *FirstSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.titlebox1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titlebox1: prismic.RichTextField;

  /**
   * ParagraphBox1 field in *FirstSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.paragraphbox1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphbox1: prismic.RichTextField;

  /**
   * LinkBox2 field in *FirstSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.linkbox2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbox2: prismic.LinkField;

  /**
   * Picture1Box2 field in *FirstSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.picture1box2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture1box2: prismic.ImageField<never>;

  /**
   * Picture2Box2 field in *FirstSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.picture2box2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture2box2: prismic.ImageField<never>;

  /**
   * TitleBox2 field in *FirstSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.titlebox2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titlebox2: prismic.RichTextField;

  /**
   * ParagraphBox2 field in *FirstSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: first_section.primary.paragraphbox2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphbox2: prismic.RichTextField;
}

/**
 * Default variation for FirstSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FirstSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FirstSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FirstSection*
 */
type FirstSectionSliceVariation = FirstSectionSliceDefault;

/**
 * FirstSection Shared Slice
 *
 * - **API ID**: `first_section`
 * - **Description**: FirstSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FirstSectionSlice = prismic.SharedSlice<
  "first_section",
  FirstSectionSliceVariation
>;

/**
 * Primary content in *Footer → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Title field in *Footer → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Footer → Items*
 */
export interface FooterSliceDefaultItem {
  /**
   * Label field in *Footer → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.items[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField;

  /**
   * Link field in *Footer → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  Simplify<FooterSliceDefaultItem>
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *FourthSection → Primary*
 */
export interface FourthSectionSliceDefaultPrimary {
  /**
   * Title field in *FourthSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fourth_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * ButtonLink field in *FourthSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fourth_section.primary.buttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonlink: prismic.LinkField;

  /**
   * ButtonLabel field in *FourthSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fourth_section.primary.buttonlabel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  buttonlabel: prismic.RichTextField;
}

/**
 * Primary content in *FourthSection → Items*
 */
export interface FourthSectionSliceDefaultItem {
  /**
   * Icon1 field in *FourthSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fourth_section.items[].icon1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon1: prismic.ImageField<never>;

  /**
   * Icon2 field in *FourthSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: fourth_section.items[].icon2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon2: prismic.ImageField<never>;

  /**
   * TitleBox field in *FourthSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fourth_section.items[].titlebox
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titlebox: prismic.RichTextField;

  /**
   * ParagraphBox field in *FourthSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fourth_section.items[].paragraphbox
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraphbox: prismic.RichTextField;

  /**
   * LinkBox field in *FourthSection → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: fourth_section.items[].linkbox
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbox: prismic.LinkField;
}

/**
 * Default variation for FourthSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourthSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FourthSectionSliceDefaultPrimary>,
  Simplify<FourthSectionSliceDefaultItem>
>;

/**
 * Slice variation for *FourthSection*
 */
type FourthSectionSliceVariation = FourthSectionSliceDefault;

/**
 * FourthSection Shared Slice
 *
 * - **API ID**: `fourth_section`
 * - **Description**: FourthSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourthSectionSlice = prismic.SharedSlice<
  "fourth_section",
  FourthSectionSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * HeroTitle field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.herotitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  herotitle: prismic.RichTextField;

  /**
   * HeroParagraph field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heroparagraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heroparagraph: prismic.RichTextField;

  /**
   * Picture1 field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.picture1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture1: prismic.ImageField<never>;

  /**
   * Picture2 field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.picture2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture2: prismic.ImageField<never>;

  /**
   * TextButton1 field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.textbutton1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textbutton1: prismic.RichTextField;

  /**
   * LinkButton1 field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.linkbutton1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton1: prismic.LinkField;

  /**
   * TextButton2 field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.textbutton2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  textbutton2: prismic.RichTextField;

  /**
   * LinkButton2 field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.linkbutton2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkbutton2: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *SecondSection → Primary*
 */
export interface SecondSectionSliceDefaultPrimary {
  /**
   * BGColor field in *SecondSection → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.bgcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bgcolor: prismic.SelectField<"Grey" | "Purple">;

  /**
   * Title field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * ButtonLabel field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.buttonlabel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  buttonlabel: prismic.RichTextField;

  /**
   * Button Link field in *SecondSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Picture field in *SecondSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Logo1 field in *SecondSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.logo1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo1: prismic.ImageField<never>;

  /**
   * SmallTitle1 field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.smalltitle1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  smalltitle1: prismic.RichTextField;

  /**
   * SmallParagraph1 field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.smallparagraph1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  smallparagraph1: prismic.RichTextField;

  /**
   * Logo2 field in *SecondSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.logo2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo2: prismic.ImageField<never>;

  /**
   * SmallTitle2 field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.smalltitle2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  smalltitle2: prismic.RichTextField;

  /**
   * SmallParagraph2 field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.smallparagraph2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  smallparagraph2: prismic.RichTextField;

  /**
   * Logo3 field in *SecondSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.logo3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo3: prismic.ImageField<never>;

  /**
   * SmallTittle3 field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.smalltittle3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  smalltittle3: prismic.RichTextField;

  /**
   * SmallParagraph3 field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.smallparagraph3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  smallparagraph3: prismic.RichTextField;
}

/**
 * Default variation for SecondSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SecondSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SecondSection → Primary*
 */
export interface SecondSectionSlicePictureReversePrimary {
  /**
   * BGColor field in *SecondSection → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.bgcolor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  bgcolor: prismic.SelectField<"Grey" | "Purple">;

  /**
   * Picture field in *SecondSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  picture: prismic.ImageField<never>;

  /**
   * Title field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Logo1 field in *SecondSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.logo1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo1: prismic.ImageField<never>;

  /**
   * SmallParagraph1 field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.smallparagraph1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  smallparagraph1: prismic.RichTextField;

  /**
   * Logo2 field in *SecondSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.logo2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo2: prismic.ImageField<never>;

  /**
   * SmallParagraph2 field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.smallparagraph2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  smallparagraph2: prismic.RichTextField;

  /**
   * Logo3 field in *SecondSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.logo3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo3: prismic.ImageField<never>;

  /**
   * SmallParagraph3 field in *SecondSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_section.primary.smallparagraph3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  smallparagraph3: prismic.RichTextField;
}

/**
 * PictureReverse variation for SecondSection Slice
 *
 * - **API ID**: `pictureReverse`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondSectionSlicePictureReverse = prismic.SharedSliceVariation<
  "pictureReverse",
  Simplify<SecondSectionSlicePictureReversePrimary>,
  never
>;

/**
 * Slice variation for *SecondSection*
 */
type SecondSectionSliceVariation =
  | SecondSectionSliceDefault
  | SecondSectionSlicePictureReverse;

/**
 * SecondSection Shared Slice
 *
 * - **API ID**: `second_section`
 * - **Description**: SecondSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondSectionSlice = prismic.SharedSlice<
  "second_section",
  SecondSectionSliceVariation
>;

/**
 * Primary content in *Text → Primary*
 */
export interface TextSliceDefaultPrimary {
  /**
   * Text field in *Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text.primary.txt
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  txt: prismic.RichTextField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<"text", TextSliceVariation>;

/**
 * Primary content in *ThirdSection → Primary*
 */
export interface ThirdSectionSliceDefaultPrimary {
  /**
   * Title field in *ThirdSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: third_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph field in *ThirdSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: third_section.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * ButtonLabel field in *ThirdSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: third_section.primary.buttonlabel
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  buttonlabel: prismic.RichTextField;

  /**
   * ButtonLink field in *ThirdSection → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: third_section.primary.buttonlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  buttonlink: prismic.LinkField;
}

/**
 * Primary content in *ThirdSection → Items*
 */
export interface ThirdSectionSliceDefaultItem {
  /**
   * Logo field in *ThirdSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: third_section.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for ThirdSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThirdSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ThirdSectionSliceDefaultPrimary>,
  Simplify<ThirdSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ThirdSection*
 */
type ThirdSectionSliceVariation = ThirdSectionSliceDefault;

/**
 * ThirdSection Shared Slice
 *
 * - **API ID**: `third_section`
 * - **Description**: ThirdSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThirdSectionSlice = prismic.SharedSlice<
  "third_section",
  ThirdSectionSliceVariation
>;

/**
 * Primary content in *BrunoText → Primary*
 */
export interface BrunoTextSliceDefaultPrimary {
  /**
   * Title field in *BrunoText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bruno_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Text field in *BrunoText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bruno_text.primary.txt
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  txt: prismic.RichTextField;

  /**
   * LastUpdate field in *BrunoText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bruno_text.primary.lastupdate
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  lastupdate: prismic.RichTextField;
}

/**
 * Default variation for BrunoText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrunoTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrunoTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BrunoText*
 */
type BrunoTextSliceVariation = BrunoTextSliceDefault;

/**
 * BrunoText Shared Slice
 *
 * - **API ID**: `bruno_text`
 * - **Description**: BrunoText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrunoTextSlice = prismic.SharedSlice<
  "bruno_text",
  BrunoTextSliceVariation
>;

/**
 * Primary content in *Hero404 → Primary*
 */
export interface Hero404SliceDefaultPrimary {
  /**
   * Title field in *Hero404 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero404.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Paragraph field in *Hero404 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero404.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * Button - Text field in *Hero404 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero404.primary.btntxt
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  btntxt: prismic.KeyTextField;

  /**
   * Button - Link field in *Hero404 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero404.primary.btnlnk
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  btnlnk: prismic.LinkField;

  /**
   * Image field in *Hero404 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero404.primary.img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img: prismic.ImageField<never>;
}

/**
 * Default variation for Hero404 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero404SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<Hero404SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero404*
 */
type Hero404SliceVariation = Hero404SliceDefault;

/**
 * Hero404 Shared Slice
 *
 * - **API ID**: `hero404`
 * - **Description**: Hero404
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type Hero404Slice = prismic.SharedSlice<
  "hero404",
  Hero404SliceVariation
>;

/**
 * Primary content in *HeroHome → Primary*
 */
export interface HeroHomeSliceDefaultPrimary {
  /**
   * Title field in *HeroHome → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for HeroHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroHome*
 */
type HeroHomeSliceVariation = HeroHomeSliceDefault;

/**
 * HeroHome Shared Slice
 *
 * - **API ID**: `hero_home`
 * - **Description**: HeroHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHomeSlice = prismic.SharedSlice<
  "hero_home",
  HeroHomeSliceVariation
>;

/**
 * Primary content in *HeroLegals → Primary*
 */
export interface HeroLegalsSliceDefaultPrimary {
  /**
   * Title field in *HeroLegals → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_legals.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Default variation for HeroLegals Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroLegalsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroLegalsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroLegals*
 */
type HeroLegalsSliceVariation = HeroLegalsSliceDefault;

/**
 * HeroLegals Shared Slice
 *
 * - **API ID**: `hero_legals`
 * - **Description**: HeroLegals
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroLegalsSlice = prismic.SharedSlice<
  "hero_legals",
  HeroLegalsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      AssuranceDocument,
      AssuranceDocumentData,
      AssuranceDocumentDataSlicesSlice,
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogCategorieDocument,
      BlogCategorieDocumentData,
      CookieDocument,
      CookieDocumentData,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialsItem,
      FooterDocumentDataSlices1Slice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataButtonchoiceItem,
      HeaderDocumentDataLowtitleItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LegalsDocument,
      LegalsDocumentData,
      LegalsDocumentDataSlicesSlice,
      LogoBankDocument,
      LogoBankDocumentData,
      LogoBankDocumentDataGrpItem,
      P404Document,
      P404DocumentData,
      P404DocumentDataSlicesSlice,
      RedirectDocument,
      RedirectDocumentData,
      RedirectDocumentDataRedirectItem,
      ShareArticleDocument,
      ShareArticleDocumentData,
      ShareArticleDocumentDataGrpItem,
      SocialMediaDocument,
      SocialMediaDocumentData,
      SocialMediaDocumentDataGrpItem,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      FifthSectionSlice,
      FifthSectionSliceDefaultPrimary,
      FifthSectionSliceDefaultItem,
      FifthSectionSliceNobuttonPrimary,
      FifthSectionSliceNobuttonItem,
      FifthSectionSliceVariation,
      FifthSectionSliceDefault,
      FifthSectionSliceNobutton,
      FirstSectionSlice,
      FirstSectionSliceDefaultPrimary,
      FirstSectionSliceVariation,
      FirstSectionSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceDefaultItem,
      FooterSliceVariation,
      FooterSliceDefault,
      FourthSectionSlice,
      FourthSectionSliceDefaultPrimary,
      FourthSectionSliceDefaultItem,
      FourthSectionSliceVariation,
      FourthSectionSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      SecondSectionSlice,
      SecondSectionSliceDefaultPrimary,
      SecondSectionSlicePictureReversePrimary,
      SecondSectionSliceVariation,
      SecondSectionSliceDefault,
      SecondSectionSlicePictureReverse,
      TextSlice,
      TextSliceDefaultPrimary,
      TextSliceVariation,
      TextSliceDefault,
      ThirdSectionSlice,
      ThirdSectionSliceDefaultPrimary,
      ThirdSectionSliceDefaultItem,
      ThirdSectionSliceVariation,
      ThirdSectionSliceDefault,
      BrunoTextSlice,
      BrunoTextSliceDefaultPrimary,
      BrunoTextSliceVariation,
      BrunoTextSliceDefault,
      Hero404Slice,
      Hero404SliceDefaultPrimary,
      Hero404SliceVariation,
      Hero404SliceDefault,
      HeroHomeSlice,
      HeroHomeSliceDefaultPrimary,
      HeroHomeSliceVariation,
      HeroHomeSliceDefault,
      HeroLegalsSlice,
      HeroLegalsSliceDefaultPrimary,
      HeroLegalsSliceVariation,
      HeroLegalsSliceDefault,
    };
  }
}
