// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  first_section: dynamic(() => import("./FirstSection")),
  footer: dynamic(() => import("./Footer")),
  fourth_section: dynamic(() => import("./FourthSection")),
  hero: dynamic(() => import("./Hero")),
  second_section: dynamic(() => import("./SecondSection")),
  text: dynamic(() => import("./Text")),
  third_section: dynamic(() => import("./ThirdSection")),
};
